import xbmcaddon
import base64

MainBase = base64.b64decode ('aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0FERE9OQkFTRS9hZGRvbnNiYXNlL21hc3Rlci9jbWN2YzIxa1ltRnpkamhxTDJaaGJtRnlkQzVxY0djOEwyWmhibUZ5ZEQ0S1BDOXBkR1Z0UGdvZ0Nnb0tJQW9nQ2lBS0lBbzhMMmwwWlcxelBnJTNEJTNELnhtbA==')
addon = xbmcaddon.Addon('script.module.live.sports.addon')